version: "1"
rules:                      # Array of rules
  - base: upstream_master   # Required. Target branch
    upstream: rtmros_choreonoid:master    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.